//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSC1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public System.Guid AccountID { get; set; }
        public byte TypeID { get; set; }
        public string EmployeeNumber { get; set; }
    
        public virtual User User { get; set; }
    }
}
